#include <drivers/dev_disk.h>
#include <printk.h>
void disk_init() {
	if (DEV_ADDR(DEV_DISK_REGADDRESS,DEV_DISK_DEVICEID) != 2) {
		panic("device id is not 2!\n");
	}
	DEV_ADDR(DEV_DISK_REGADDRESS,DEV_DISK_STATUS) = 0;
	DEV_ADDR(DEV_DISK_REGADDRESS,DEV_DISK_STATUS) = ACKNOWLEDGE;
	DEV_ADDR(DEV_DISK_REGADDRESS,DEV_DISK_STATUS) = DRIVER;
	DEV_ADDR(DEV_DISK_REGADDRESS,DEV_DISK_STATUS) = FEATHERS_OK;
	if(DEV_ADDR(DEV_DISK_REGADDRESS,DEV_DISK_STATUS) != FEATHERS_OK) {
		panic("device is not feathers ok!\n");
	}	
	DEV_ADDR(DEV_DISK_REGADDRESS,DEV_DISK_STATUS) = DRIVER_OK;

}
